language: generic
dist: trusty
env:
  - VERSION=25.2.2 EMACS=emacs-25.2 PACKAGE=emacs25
  - VERSION=25.2.2 EMACS=emacs-25.2 PACKAGE=emacs25 CLJ_PARSE_LINT=true

matrix:
  allow_failures:
    - env: VERSION=25.2.2 EMACS=emacs-25.2 PACKAGE=emacs25 CLJ_PARSE_LINT=true

before_install:
  - sudo add-apt-repository -y ppa:kelleyk/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq $PACKAGE

script:
  - $EMACS --version
  - ls /usr/bin /usr/local/bin | grep emacs
  - $EMACS --version | grep $VERSION
  - $EMACS -batch -l clj-parse-test-runner.el
